# Generated by Django 4.0.5 on 2022-06-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foundation_Name', models.CharField(max_length=100)),
                ('Focus_area', models.TextField(blank=True, null=True)),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.FloatField(max_length=20)),
                ('Website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
