# Generated by Django 4.0.5 on 2022-06-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='Address',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foundation',
            name='Phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
