# Generated by Django 4.0.5 on 2022-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_alter_foundation_address_alter_foundation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='Address',
            field=models.CharField(max_length=100),
        ),
    ]
